### ISSUE TITLE
State parameter does not matched

### ISSUE THREAD

**Issue by bitpickle** [AdnanHussainTurki/microsoft-api-php#1]
The line `$tokens = $auth->getToken($_REQUEST['code'], $_REQUEST['state']);` is returning an error:

"State parameter does not matched"

I think that is something with the version.

**Comment by rmcnulty** [comment]
This will fix it for you
On line 13 of callback.php:
if ( !empty($_REQUEST['state']) ) { Session::set('state', $_REQUEST['state']) }
