### ISSUE TITLE
cURL error 60: SSL certificate problem

### ISSUE THREAD

**Issue by Amorpl21** [AdnanHussainTurki/microsoft-api-php#5]
how to fix it?
Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate

**Comment by nizzam** [comment]
Hi @Amorpl21 ,

I experience the same issue. Have you found any solutions ?

**Comment by AdnanHussainTurki** [comment]
The problem is due to the non-SSL nature of localhost, we will soon ruling out a function call which can disable SSL verification (only for local testing).

**Comment by AdnanHussainTurki** [comment]
The last argument of the constructor accepts boolean arguments which allow support for non-SSL scenarios.

Turn off SSL Verify:
```
$microsoft = new Auth($tenant, $client_id, $client_secret,$callback, $scopes, false);
```

Warning : Turning off SSL in production environment is NOT RECOMMEDED.
